<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

genesis_structural_wrap( 'site-inner', 'close' );
genesis_markup(
	array(
		'close'   => '</div>',
		'context' => 'site-inner',
	)
);

/**
 * Fires immediately after the site inner closing markup, before `genesis_footer` action hook.
 *
 * @since 1.0.0
 */
do_action( 'genesis_before_footer' );
$f_left = get_field('footer_left');
extract($f_left);
$f_center = get_field('footer_center');
extract($f_center);
$f_right = get_field('footer_right');
extract($f_right);
?>
<div class="footer-custom">
	<div class="container">
		<div class="col-md-4">
			<div class="footer-left">
				<div class="social-ft">
					<h3 class="title-sc"><?php if ($social_title) echo esc_html($social_title); ?></h3>
					<ul class="list-inline-block">
						<li>
							<a href="<?php if ($facebook_social) echo esc_html($facebook_social); ?>">
								<img src="<?php echo get_stylesheet_directory_uri(); ?>/assets/images/fb.png" alt="Crossfit-Facebook"/>
							</a>
						</li>
						<li>
							<a href="<?php if ($youtube_social) echo esc_html($youtube_social); ?>">
								<img src="<?php echo get_stylesheet_directory_uri(); ?>/assets/images/yt.png" alt="Crossfit-Youtube"/>
							</a>
						</li>
						<li>
							<a href="<?php if ($google_plus) echo esc_html($google_plus); ?>">
								<img src="<?php echo get_stylesheet_directory_uri(); ?>/assets/images/gg.png" alt="Crossfit-Google Plus"/>
							</a>
						</li>
						<li>
							<a href="<?php if ($pinterest) echo esc_html($pinterest); ?>">
								<img src="<?php echo get_stylesheet_directory_uri(); ?>/assets/images/pin.png" alt="Crossfit-Pinterest"/>
							</a>
						</li>
						<li>
							<a href="<?php if ($twitter) echo esc_html($twitter); ?>">
								<img src="<?php echo get_stylesheet_directory_uri(); ?>/assets/images/tw.png" alt="Crossfit-Twitter"/>
							</a>
						</li>
					</ul>
				</div>
				<div class="phone-ft text-center">
					<h3 class="title-sc title-pn"><?php if ($phone_tilte) echo esc_html($phone_tilte); ?></h3>
					<a class="phone-num" href="<?php echo esc_html($phone_number); ?>"><?php if ($phone_number) echo esc_html($phone_number); ?></a>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="footer-center">
				<div class="ft-logo">
					<a href="<?php echo esc_url(home_url('/')); ?>">
						<?php if ($ft_logo) echo '<img class="logo-footer" src="' . wp_get_attachment_url( $ft_logo ) . '"/>'; ?>
					</a>
				</div>
				<div class="ft-btn">
					<?php if ($ft_btn_title) : ?>
					<a href="<?php echo esc_html($ft_btn_url); ?>" class="btn-crossfit"><?php echo esc_html($ft_btn_title); ?></a>
					<?php endif; ?>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="footer-right">
				<div class="ft-add">
					<h3 class="title-sc"><?php if ($ft_righ_title) echo esc_html($ft_righ_title); ?></h3>
					<p class="add-info"><?php if ($ft_add) echo esc_html($ft_add); ?></p>
				</div>
				<div class="ft-part">
					<h3 class="title-sc"><?php if ($par_title) echo esc_html($par_title); ?></h3>
					<div class="list-img">
						<?php if ($part_list_img) echo apply_filters('crossfit_output_content', $part_list_img)  ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>



<?php
/**
 * Fires to display the main footer content.
 *
 * @since 1.0.1
 */
// do_action( 'genesis_footer' );

/**
 * Fires immediately after the `genesis_footer` action hook, before the site container closing markup.
 *
 * @since 1.0.0
 */
do_action( 'genesis_after_footer' );

genesis_markup(
	array(
		'close'   => '</div>',
		'context' => 'site-container',
	)
);

/**
 * Fires immediately before wp_footer(), after the site container closing markup.
 *
 * @since 1.0.0
 */
do_action( 'genesis_after' );


wp_footer(); // We need this for plugins.

genesis_markup(
	array(
		'close'   => '</body>',
		'context' => 'body',
	)
);

?>
</html>
